//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.02 at 01:12:40 PM EEST 
//

package realestateagency.service.models;


import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "agent", propOrder = {"id", "name", "age", "phoneNumber"})
public class Agent
{

    protected int id;

    @XmlElement(required = true)
    protected String name;

    @XmlElement(required = true)
    protected int age;

    @XmlElement(name = "phone-number", required = true)
    protected String phoneNumber;


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("╔═══════════╦═════════════╦═════════╦═════════════════╗\n");
        sb.append(String.format("║ %-10s║ %-12s║ %-8s║ %-16s║\n", "ID", "Name", "Age", "Phone Number"));
        sb.append("╠═══════════╬═════════════╬═════════╬═════════════════╣\n");
        sb.append(String.format("║ %-10d║ %-12s║ %-8d║ %-16s║\n", id, name, age, phoneNumber));
        sb.append("╚═══════════╩═════════════╩═════════╩═════════════════╝\n");
        return sb.toString();
    }

}