//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.02 at 01:12:40 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://real-estate-agency",
                                       elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package realestateagency.service.models;
